project:
  type: website
  output-dir: ../_site

website:
  title: "OmniQ"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: installation.qmd
        text: Installation
      - href: quickstart.qmd
        text: Quickstart
      - text: API Reference
        menu:
          - href: api/backends.md
            text: Backends
          - href: api/configuration.md
            text: Configuration
          - href: api/events.md
            text: Events
          - href: api/storage.md
            text: Storage
          - href: api/task_queues.md
            text: Task Queues
          - href: api/workers.md
            text: Workers
      - href: examples.qmd
        text: Examples
      - href: advanced.qmd
        text: Advanced Usage
      - href: contributing.qmd
        text: Contributing

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

